language: go

go:
  - 1.7


before_install:
  - mkdir /home/travis/gopath/bin &> /dev/null; if [ $? -ne 0 ]; then curl https://glide.sh/get | sh; fi
  - make dep_install

script:
  - make test

cache:
  directories:
  - vendor
  - /home/travis/gopath/bin
